/**
 * Memory Store — OpenClaw Memory Core backed task persistence
 *
 * Stores tasks as Markdown files in the OpenClaw workspace memory directory:
 *   <workspace>/memory/subagent-tasks/<taskId>.md
 *
 * Each file contains a Markdown header + JSON code block, e.g.:
 *   # Task: task_xxx
 *   ```json
 *   { "id": "task_xxx", "description": "...", "status": "open", ... }
 *   ```
 *
 * OpenClaw's memory-core plugin automatically:
 *   - Watches the memory/ directory for changes
 *   - Rebuilds the SQLite FTS5 + vector index (debounced ~1.5s)
 *   - Powers memory_search with keyword + semantic search
 *
 * Benefits:
 *   - Zero new storage locations — reuses OpenClaw's native memory system
 *   - Built-in search (BM25 FTS5 + embeddings) — no need to implement ourselves
 *   - Auto-reindex on file change — no manual index maintenance
 *   - Follows OpenClaw upgrades automatically — no version coupling
 *   - No extra config for users — works out of the box with workspace mount
 */

import * as fs from "fs";
import * as path from "path";

/** Directory under workspace where task files live */
export const TASKS_SUBDIR = "memory/subagent-tasks";

/** Comment prefix embedded in file header */
const HEADER_COMMENT = `<!-- This file is auto-generated by subagent-coordinator taskr plugin.
     Edit via the update_task tool or directly if you know what you're doing.
     Memory Core will re-index this file automatically. -->
`;

/**
 * Resolve the workspace memory tasks directory.
 *
 * Priority:
 *   1. OPENCLAW_WORKSPACE env (set by OpenClaw runtime)
 *   2. HOME/.openclaw/workspace (default)
 *   3. Current working directory (last resort)
 */
function resolveTasksDir(): string {
  const workspace = process.env.OPENCLAW_WORKSPACE
    || path.join(process.env.HOME || "/root", ".openclaw/workspace");
  return path.join(workspace, TASKS_SUBDIR);
}

/**
 * Serialize a task object into Markdown file content.
 * The JSON is stored in a fenced code block so:
 *   - Memory Core indexes the plain text (header, fields)
 *   - We can parse it back by extracting the code block
 *   - Human editors can also read and edit the file
 */
function serializeTaskToMarkdown(task: Record<string, unknown>): string {
  const header = `# Task: ${task.id}`;
  const json = JSON.stringify(task, null, 2);
  return `${HEADER_COMMENT}${header}\n\n\`\`\`json\n${json}\n\`\`\`\n`;
}

/**
 * Deserialize a Markdown file back to a task object.
 * Extracts the first JSON code block from the file.
 *
 * Returns null if:
 *   - File doesn't exist
 *   - No ```json block found
 *   - JSON is unparsable
 */
function deserializeTaskFromMarkdown(filePath: string): Record<string, unknown> | null {
  try {
    const content = fs.readFileSync(filePath, "utf8");
    const match = content.match(/```json\s*([\s\S]*?)\s*```/);
    if (!match) return null;
    return JSON.parse(match[1].trim()) as Record<string, unknown>;
  } catch {
    return null;
  }
}

/**
 * Check if a task file exists on disk.
 */
function taskFileExists(taskId: string): boolean {
  const filePath = path.join(resolveTasksDir(), `${taskId}.md`);
  return fs.existsSync(filePath);
}

// ─────────────────────────────────────────────────────────────────────────────
// MemoryPersistenceService — implements PersistenceService interface
// ─────────────────────────────────────────────────────────────────────────────

export interface MemoryPersistenceConfig {
  /** Subdirectory under workspace (default: memory/subagent-tasks) */
  subdir?: string;
  /** Emit console warnings for indexing delays (default: false) */
  warnIndexDelay?: boolean;
}

export interface MemoryPersistenceState {
  config: Required<MemoryPersistenceConfig>;
  initialized: boolean;
}

export interface MemoryPersistenceService {
  /**
   * Save a task object to a Markdown file.
   * File path: <workspace>/memory/subagent-tasks/<task.id>.md
   *
   * The task will appear in memory_search within ~1.5s (memory-core debounce).
   */
  saveTask(task: Record<string, unknown>): Promise<void>;

  /**
   * Load a single task by ID.
   * Returns null if not found or unparsable.
   */
  loadTask(taskId: string): Promise<Record<string, unknown> | null>;

  /**
   * Load all tasks, optionally filtered by a predicate.
   * Returns tasks sorted by createdAt descending (newest first).
   */
  loadAllTasks(filter?: (task: Record<string, unknown>) => boolean): Promise<Record<string, unknown>[]>;

  /**
   * Delete a task file.
   * Returns true if deleted, false if didn't exist.
   */
  deleteTask(taskId: string): Promise<boolean>;

  /**
   * Check if a task file exists on disk.
   */
  hasTask(taskId: string): Promise<boolean>;

  /**
   * List all task IDs currently on disk.
   */
  listTaskIds(): Promise<string[]>;

  /**
   * Get the workspace path for task files (for debugging/inspection).
   */
  getTasksDir(): string;
}

export function createMemoryStore(
  state: MemoryPersistenceState
): MemoryPersistenceService {
  const { warnIndexDelay } = state.config;

  function ensureDir(): void {
    const dir = resolveTasksDir();
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  function getFilePath(taskId: string): string {
    return path.join(resolveTasksDir(), `${taskId}.md`);
  }

  return {
    async saveTask(task: Record<string, unknown>): Promise<void> {
      if (!task.id || typeof task.id !== "string") {
        throw new Error("Task must have a string 'id' field");
      }
      ensureDir();
      const filePath = getFilePath(task.id);
      const content = serializeTaskToMarkdown(task);
      fs.writeFileSync(filePath, content, "utf8");
      if (warnIndexDelay) {
        console.warn(`[taskr:memory] Task ${task.id} saved. Memory search will index it within ~1.5s.`);
      }
    },

    async loadTask(taskId: string): Promise<Record<string, unknown> | null> {
      const filePath = getFilePath(taskId);
      if (!fs.existsSync(filePath)) return null;
      return deserializeTaskFromMarkdown(filePath);
    },

    async loadAllTasks(filter?: (task: Record<string, unknown>) => boolean): Promise<Record<string, unknown>[]> {
      const dir = resolveTasksDir();
      if (!fs.existsSync(dir)) return [];

      const files = fs.readdirSync(dir).filter(f => f.endsWith(".md"));
      const tasks: Record<string, unknown>[] = [];

      for (const file of files) {
        const taskId = file.replace(/\.md$/, "");
        const task = await this.loadTask(taskId);
        if (task && (!filter || filter(task))) {
          tasks.push(task);
        }
      }

      // Sort newest first
      return tasks.sort((a, b) => {
        const aTime = (a.createdAt as number) || 0;
        const bTime = (b.createdAt as number) || 0;
        return bTime - aTime;
      });
    },

    async deleteTask(taskId: string): Promise<boolean> {
      const filePath = getFilePath(taskId);
      if (!fs.existsSync(filePath)) return false;
      fs.unlinkSync(filePath);
      return true;
    },

    async hasTask(taskId: string): Promise<boolean> {
      return taskFileExists(taskId);
    },

    async listTaskIds(): Promise<string[]> {
      const dir = resolveTasksDir();
      if (!fs.existsSync(dir)) return [];
      return fs.readdirSync(dir)
        .filter(f => f.endsWith(".md"))
        .map(f => f.replace(/\.md$/, ""));
    },

    getTasksDir(): string {
      return resolveTasksDir();
    },
  };
}

export function createMemoryStoreState(
  config: MemoryPersistenceConfig = {}
): MemoryPersistenceState {
  return {
    config: {
      subdir: config.subdir ?? TASKS_SUBDIR,
      warnIndexDelay: config.warnIndexDelay ?? false,
    },
    initialized: false,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
// Backwards-compatible wrapper — wraps MemoryPersistenceService
// as a PersistenceService so task_store.ts doesn't need changes
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Create a PersistenceService-compatible wrapper around MemoryPersistenceService.
 * This allows dropping in memory_store as a replacement for file-based persistence
 * in createTaskStore(taskStoreState, persistenceService).
 *
 * The wrapper translates:
 *   save("task_store", data)     → saveTask(task) for each task + saveNotes()
 *   load("task_store")          → loadAllTasks() → reconstruct state
 *   delete("task_store")        → not supported (would delete all tasks)
 *
 * Note: This is a best-effort translation. The raw MemoryPersistenceService
 * gives each task its own file (better for memory indexing). The wrapper
 * is provided for environments where you want to keep task_store.ts unchanged.
 */
export function createMemoryPersistenceWrapper(
  memoryStore: MemoryPersistenceService
): {
  save(key: string, data: unknown): Promise<void>;
  load<T>(key: string): Promise<T | null>;
  delete(key: string): Promise<boolean>;
  exists(key: string): Promise<boolean>;
  list(prefix?: string): Promise<string[]>;
} {
  return {
    async save(key: string, data: unknown): Promise<void> {
      // data is { tasks: [id, Task][], notes: [id, Note[]][], dependencies: [id, string[]][] }
      const payload = data as {
        tasks?: [string, Record<string, unknown>][];
        notes?: [string, unknown][];
        dependencies?: [string, string[]][];
      };

      if (payload.tasks) {
        for (const [taskId, task] of payload.tasks) {
          await memoryStore.saveTask({ ...task, id: taskId });
        }
      }
      // notes and dependencies are stored as part of the task metadata
      // when task_store serializes them — no separate handling needed
    },

    async load<T>(key: string): Promise<T | null> {
      try {
        const tasks = await memoryStore.loadAllTasks();
        const notesMap = new Map<string, unknown[]>();
        const depsMap = new Map<string, string[]>();

        // Extract notes and dependencies from task metadata
        for (const task of tasks) {
          if (task.notes) {
            notesMap.set(task.id as string, task.notes as unknown[]);
          }
          if (task.dependencies) {
            depsMap.set(task.id as string, task.dependencies as string[]);
          }
        }

        return {
          tasks: tasks.map(t => [t.id, t] as [string, Record<string, unknown>]),
          notes: Array.from(notesMap.entries()),
          dependencies: Array.from(depsMap.entries()),
        } as T;
      } catch {
        return null;
      }
    },

    async delete(_key: string): Promise<boolean> {
      // Deleting the whole store would require iterating all tasks — not supported
      return false;
    },

    async exists(key: string): Promise<boolean> {
      const tasks = await memoryStore.loadAllTasks();
      return tasks.length > 0;
    },

    async list(_prefix?: string): Promise<string[]> {
      return ["task_store"]; // We only have one logical "key"
    },
  };
}
