# vllm版本信息
vllm_version: 0.17.0

# 模型名称
infer_model_name: Qwen3.5-27B

# 模型权重路径
infer_mode_path: /path/to/models/Qwen35_27B

# 是否开启专家并行, MOE模型默认需要开启, Dense模型需要关闭
enable_expert_parallel: false

# 推理部署是否使用PD分离, 1:PD separate, 0:PD hybrid
pd_mode: 0

# prefill实例数量
prefill_instance_count: 1

# decode实例数量, 注意：PD混部时decode实例数要配置为0
decode_instance_count: 0

# prefill/decode tp size
tensor_parallel_size: 4

# prefill/decode dp size
data_parallel_size: 2

# 模型输出最大长度
max_model_len: 65536

# max-num-batched-tokens
max_num_batched_tokens: 8192

# gpu-memory-utilization
gpu_memory_utilization: 0.6

# max-num-seqs
max_num_seqs: 16

# 图模式的capture size
cudagraph_capture_sizes: [4,8,12,16,24]

# kv cache PD之间同步传输后端: mooncake 或 llmdatadist
kv_backend: mooncake

# 统计开关
enable_vllm_stat: false

# 权重相似度检查开关
enable_tensor_similarity_check: false

# flash comm算法支持: 0关闭, 1开启
vllm_ascend_enable_flashcomm: 0
vllm_ascend_enable_flashcomm1: 0

# 是否使用优化vllm
use_vllm_opt: true
