FROM swr.cn-south-1.myhuaweicloud.com/ascendhub/cann:9.0.0-a3-openeuler24.03-py3.11
ENV SOC_VERSION=ascend910_9391 \
    DEBIAN_FRONTEND=noninteractive \
    LANG=en_US.UTF-8 \
    LC_ALL=en_US.UTF-8

ARG GIT_BRANCH=master

RUN yum -y update && \
    yum -y install net-tools dos2unix ca-certificates curl wget numactl jemalloc clang patch && \
    update-ca-trust || true && \
    yum clean all && \
    rm -rf /var/cache/yum && \
    echo 'set encoding=utf-8' >> /etc/vimrc

RUN mkdir -p /home/work

WORKDIR /home/work

RUN git clone -b ${GIT_BRANCH} https://gitcode.com/Ascend/AgentSDK.git && \
    rm -rf /home/work/AgentSDK/aura/tests && \
    bash /home/work/AgentSDK/docker/aura/env/build_repos.sh

RUN pip config set global.index-url https://mirrors.aliyun.com/pypi/simple/ && \
    pip config set global.trusted-host "mirrors.aliyun.com mirrors.huaweicloud.com" && \
    pip install torch==2.10.0+cpu --index-url https://download.pytorch.org/whl/cpu && \
    cd /verl && \
    git checkout e9972368aa6a6078eacd7f0678bdfdd0196ce7b5 && \
    pip install -r requirements-npu.txt && \
    pip install -v -e . && \
    pip cache purge || true

RUN PYTHONUNBUFFERED=1 VLLM_TARGET_DEVICE="empty" pip install -v -e /home/work/vllm/[audio] && \
    pip uninstall -y triton && \
    export PIP_EXTRA_INDEX_URL="https://mirrors.huaweicloud.com/ascend/repos/pypi" && \
    source /usr/local/Ascend/ascend-toolkit/set_env.sh && \
    source /usr/local/Ascend/cann-9.0.0/share/info/ascendnpu-ir/bin/set_env.sh && \
    source /usr/local/Ascend/nnal/atb/set_env.sh && \
    PYTHONUNBUFFERED=1 pip install -v -e /home/work/vllm-ascend/ && \
    pip uninstall -y triton triton-ascend && \
    pip install triton-ascend==3.2.1 --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi && \
    pip cache purge || true

RUN pip install -e /home/work/MindSpeed && \
    pip install -e /home/work/Megatron-LM && \
    pip install mbridge && \
    bash /home/work/AgentSDK/docker/aura/env/build_common.sh && \
    pip cache purge || true

RUN cd /verl && \
    git apply /home/work/AgentSDK/aura/third_party/patch/verl.patch && \
    cd /home/work/vllm && \
    git apply /home/work/AgentSDK/aura/third_party/patch/vllm.patch && \
    cd /home/work/vllm-ascend && \
    git apply /home/work/AgentSDK/aura/third_party/patch/vllm-ascend.patch

ENV http_proxy="" \
    https_proxy="" \
    HTTP_PROXY="" \
    HTTPS_PROXY=""

WORKDIR /home/work/AgentSDK/aura
