# vllm版本信息
vllm_version: 0.13.0

# 模型名称
infer_model_name: Qwen3-235B-thinking-2507

# 模型权重路径
infer_model_path: /path/to/models/Qwen3-235B-thinking-2507

# 是否开启专家并行, MOE模型默认需要开启, Dense模型需要关闭
enable_expert_parallel: true

# 推理部署是否使用PD分离
use_pd_separate: true

# prefill实例数量
prefill_instance_count: 1

# decode实例数量
decode_instance_count: 1

# prefill/decode tp size
tensor_parallel_size: 4

# prefill/decode dp size
data_parallel_size: 8

# 模型输出最大长度
max_model_len: 65536

# max-num-batched-tokens
max_num_batched_tokens: 8192

# gpu-memory-utilization
gpu_memory_utilization: 0.7

# max-num-seqs
max_num_seqs: 16

# 图模式的capture size
cudagraph_capture_sizes: [4,8,12,16,24]

# 图模式，未配置时沿用对应启动模式的默认值
# 可选: NONE | PIECEWISE | FULL | FULL_DECODE_ONLY | FULL_AND_PIECEWISE
cudagraph_mode: FULL_AND_PIECEWISE

# 是否开启序列并行（SP），未配置时沿用对应启动模式的默认值
enable_sp: false

# kv cache PD之间同步传输后端: mooncake 或 llmdatadist
kv_backend: mooncake

# 统计开关
enable_vllm_stat: false

# 权重相似度检查开关
enable_tensor_similarity_check: false
