# [train]
# 启动训练相关参数
# 工作模式：hybrid 共卡模式 | one_step_off 全异步分离模式
work_mode=one_step_off

# 共卡和分离模式均需要配置训练yaml文件
#train_config_name=verl_train_async_t16_qwen35_35B_A3B_dtn_code_fsdp
train_config_name=verl_train_async_t8_qwen35_27B_dtn_code_fsdp_dummy
#train_config_name=verl_train_async_t256_qwen35_122B_A10B_dtn_code_megatron

# 分离模式需要单独配置推理yaml文件, 共卡模式该配置不生效
#infer_config_name=vllm_infer_i16_qwen35_35b_A3B
infer_config_name=vllm_infer_i8_qwen35_27b
#infer_config_name=vllm_infer_i64_qwen35_122b_A10B

# [resume]
# 启动断点续训相关参数
# 需要监控的启动脚本：start_rl_with_msrl_vllm.sh | start_rl_with_verl_vllm.sh
monitor_cmd=start_rl_with_verl_vllm.sh

# 断点续训重试次数, 默认100次
max_retries=100

# 第一次启动是否需要清空ckpt文件夹: 0 不清理; 1 需要清理
clean_old_ckpt=0
