# [train]
# 启动训练相关参数
# 工作模式：hybrid 共卡模式 | one_step_off 单步异步分离模式 | fully_async 全异步分离模式
work_mode=one_step_off

# 共卡和分离模式均需要配置训练yaml文件
# 配置文件名不包含 .yaml 后缀
# train_config_name=verl_train_hybrid_A3_t16_qwen3_8b_math_fsdp
# train_config_name=verl_train_async_A3_t16_qwen3_8b_math_fsdp
# train_config_name=verl_train_hybrid_A3_t16_qwen3_32b_math_fsdp
train_config_name=verl_train_async_A3_t16_qwen3_32b_math_fsdp

# 分离模式需要单独配置推理yaml文件, 共卡模式该配置不生效
# 配置文件名不包含 .yaml 后缀
#infer_config_name=vllm_infer_i16_qwen3_8b
infer_config_name=vllm_infer_i16_qwen3_32b

# [resume]
# 启动断点续训相关参数
# 需要监控的启动脚本：start_rl_with_verl_vllm.sh
monitor_cmd=start_rl_with_verl_vllm.sh

# 断点续训重试次数, 默认100次
max_retries=100

# 第一次启动是否需要清空ckpt文件夹: 0 不清理; 1 需要清理
clean_old_ckpt=0
