# host,index,train_master_index,infer_master_index(可选)
# 如果单机训练+推理共部署, 则需要配置infer_master_index

# [单机训练+推理]
# 配置例子1：单机，训推共节点部署, 方便本地调测
# host,index,train_master_index,infer_master_index(可选)
# 7.242.102.234,0,1,1

# [多机训练+推理]
# 配置例子2：双机, 训推分离, 分节点部署
# host,index,train_master_index,infer_master_index(可选)
7.242.99.212,0,0
7.242.96.196,1,1
